# Generated by Django 2.1.7 on 2019-03-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20190329_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='autoslug',
        ),
    ]
